set(SOURCES
	src/Body/Actors.cpp
	src/Body/Actors.h
	src/Body/Morph.cpp
	src/Body/Morph.h
	src/Body/MorphProcedural.cpp
	src/Body/MorphProcedural.h
	src/Body/OBody.cpp
	src/Body/OBody.h
	src/Event/Event.h
	src/PCH.cpp
	src/PCH.h
	src/Papyrus.cpp
	src/Papyrus.h
	src/SKEE.h
	src/main.cpp
)
